### ISSUE TITLE
error with Slashes in artist or album name

### ISSUE THREAD

**Issue by streetsamurai00mi** [vitiko98/Qobuz-DL#1]
err message:
```
Traceback (most recent call last):
  File "main.py", line 125, in <module>
    sys.exit(main())
  File "main.py", line 119, in main
    interactive(Qz, directory, arguments.l, True)
  File "main.py", line 97, in interactive
    searchSelected(Qz, path, Albums, IDs, Types, quality)
  File "main.py", line 56, in searchSelected
    downloader.iterateIDs(Qz, id_[al[1]], path, quality, False)
  File "/home/username/proj/Qobuz-DL/qo_utils/downloader.py", line 88, in iterateIDs
    mkDir(dirn)
  File "/home/username/proj/Qobuz-DL/qo_utils/downloader.py", line 25, in mkDir
    os.mkdir(dirn)
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/data/Music/qo/AC/DC - Back In Black [1980]'
```

Example album:
AC/DC - Back In Black
Kaleo - A/B

**Comment by B3ATDROP3R** [comment]
I have the same issue but with the character ":"
Downloading: TRON: Legacy

Traceback (most recent call last):
  File "main.py", line 125, in <module>
    sys.exit(main())
  File "main.py", line 119, in main
    interactive(Qz, directory, arguments.l, True)
  File "main.py", line 97, in interactive
    searchSelected(Qz, path, Albums, IDs, Types, quality)
  File "main.py", line 54, in searchSelected
    downloader.iterateIDs(Qz, id_[al[1]], path, quality, True)
  File "D:\Qo-DL-Reborn-master\Qobuz-DL-master\qo_utils\downloader.py", line 62, in iterateIDs
    mkDir(dirn)
  File "D:\Qo-DL-Reborn-master\Qobuz-DL-master\qo_utils\downloader.py", line 25, in mkDir
    os.mkdir(dirn)
NotADirectoryError: [WinError 267] The directory name is invalid: 'Qobuz Downloads/Daft Punk - TRON: Legacy [2010]'

I worked around this issue by using Windows Subsystem for linux.

**Comment by vitiko98** [comment]
Thanks for the report and sorry for the late reply. I'm fixing it as soon as possible.
