### ISSUE TITLE
Error when passing a link encapsulating multiple albums

### ISSUE THREAD

**Issue by WillyCroco** [vitiko98/qobuz-dl#103]
`qobuz-dl dl https://play.qobuz.com/album/whateveralbum1234`
When trying to download a single album with the argument 'dl', everything's fine.

`qobuz-dl dl filetext`
When trying to download multiple albums with the argument 'dl', using either a link (e.g. the url of an artist, or favourite albums) or a textfile, an error is thrown :

```
AttributeError: 'NoneType' object has no attribute 'groups'

Traceback (most recent call last):
  File "/Users/user/Library/Python/3.9/bin/qobuz-dl", line 8, in <module>
    sys.exit(main())
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/qobuz_dl/cli.py", line 176, in main
    _handle_commands(qobuz, arguments)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/qobuz_dl/cli.py", line 83, in _handle_commands
    qobuz.download_list_of_urls(arguments.SOURCE)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/qobuz_dl/core.py", line 180, in download_list_of_urls
    self.handle_url(url)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/qobuz_dl/core.py", line 128, in handle_url
    url_type, item_id = get_url_info(url)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/qobuz_dl/utils.py", line 190, in get_url_info
    return r.groups()
```

Using version 0.9.9.2

**Comment by WillyCroco** [comment]
Error parsing adresses with additional formatting char. Not a bug.
