### ISSUE TITLE
Error when attempting to download a playlist

### ISSUE THREAD

**Issue by YachtSail** [vitiko98/qobuz-dl#108]
An error occurred when I attempted to download the playlist below:

C:\Users\xxxx\AppData\Local\Programs\Python\Python38-32\Scripts>qobuz-dl dl https://www.qobuz.com/us-en/playlists/6054697 -q 27
Logging...
Logged: OK
Membership: Studio
Set max quality: 27 - 24 bit, >96kHz

Traceback (most recent call last):
  File "c:\users\xxxx\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\xxxx\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38-32\Scripts\qobuz-dl.exe\__main__.py", line 7, in <module>
  File "c:\users\xxxx\appdata\local\programs\python\python38-32\lib\site-packages\qobuz_dl\cli.py", line 176, in main
    _handle_commands(qobuz, arguments)
  File "c:\users\xxxx\appdata\local\programs\python\python38-32\lib\site-packages\qobuz_dl\cli.py", line 83, in _handle_commands
    qobuz.download_list_of_urls(arguments.SOURCE)
  File "c:\users\xxxx\appdata\local\programs\python\python38-32\lib\site-packages\qobuz_dl\core.py", line 180, in download_list_of_urls
    self.handle_url(url)
  File "c:\users\xxxx\appdata\local\programs\python\python38-32\lib\site-packages\qobuz_dl\core.py", line 128, in handle_url
    url_type, item_id = get_url_info(url)
  File "c:\users\xxxx\appdata\local\programs\python\python38-32\lib\site-packages\qobuz_dl\utils.py", line 190, in get_url_info
    return r.groups()
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by YachtSail** [comment]
Problem solved. Unsupported URL type. URLs supported as found in utils.py: 

https://www.qobuz.com/us-en/{type}/{name}/{id}        https://open.qobuz.com/{type}/{id}        https://play.qobuz.com/{type}/{id}
