### ISSUE TITLE
App not downloading, possible App id/Secret issue

### ISSUE THREAD

**Issue by breadforall** [vitiko98/qobuz-dl#112]
Logged: OK
Membership: Studio
Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python38-32\Scripts\qobuz-dl.exe\__main__.py", line 7, in <module>
  File "c:\program files (x86)\python38-32\lib\site-packages\qobuz_dl\cli.py", line 174, in main
    qobuz.initialize_client(email, password, app_id, secrets)
  File "c:\program files (x86)\python38-32\lib\site-packages\qobuz_dl\core.py", line 73, in initialize_client
    self.client = qopy.Client(email, pwd, app_id, secrets)
  File "c:\program files (x86)\python38-32\lib\site-packages\qobuz_dl\qopy.py", line 39, in __init__
    self.cfg_setup()
  File "c:\program files (x86)\python38-32\lib\site-packages\qobuz_dl\qopy.py", line 200, in cfg_setup
    if self.test_secret(secret):
  File "c:\program files (x86)\python38-32\lib\site-packages\qobuz_dl\qopy.py", line 192, in test_secret
    r = self.api_call("userLibrary/getAlbumsList", sec=sec)
  File "c:\program files (x86)\python38-32\lib\site-packages\qobuz_dl\qopy.py", line 114, in api_call
    r.raise_for_status()
  File "C:\Users\1\AppData\Roaming\Python\Python38\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://www.qobuz.com/api.json/0.2/userLibrary/getAlbumsList?app_id=950096963&user_auth_token=H6WDsAQzsiSlx3KakaZvTIXbv5OI7IG7VQZWapJGLkiRfoeuBtHHiNbPJSOTeFrQqVKL--XhKggdloDb-uIQeg&request_ts=1627362045.957819&request_sig=4cbaf00a262aab17a33b8103ca9d61f6

I keep getting this error when using the qobuz-dl dl command. Get the same error on 2 different PC's with 2 different versions of python. Very likely an app id/secret issue. Used the qobuz-dl -r command and re-entered the details again but same issue.

**Comment by breadforall** [comment]
Tried again after a couple of hours and it's working now, but sometimes won't download tracks and i have to re-run the command to download. Also for some artists it takes a good minute to start the run. Probably server issues.
