### ISSUE TITLE
No longer working and hasn't in a week or so

### ISSUE THREAD

**Issue by Gamer4Life2020** [vitiko98/qobuz-dl#116]
qobuz-dl will download 44 urls from file: C:\Users\User\Desktop\qobuz.txt
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\Scripts\qobuz-dl.exe\__main__.py", line 7, in <module>
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\qobuz_dl\cli.py", line 176, in main
    _handle_commands(qobuz, arguments)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\qobuz_dl\cli.py", line 83, in _handle_commands
    qobuz.download_list_of_urls(arguments.SOURCE)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\qobuz_dl\core.py", line 178, in download_list_of_urls
    self.download_from_txt_file(url)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\qobuz_dl\core.py", line 197, in download_from_txt_file
    self.download_list_of_urls(urls)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\qobuz_dl\core.py", line 180, in download_list_of_urls
    self.handle_url(url)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\qobuz_dl\core.py", line 128, in handle_url
    url_type, item_id = get_url_info(url)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\qobuz_dl\utils.py", line 190, in get_url_info
    return r.groups()
AttributeError: 'NoneType' object has no attribute 'groups'

I'm sure your busy so no rush as there are others not sure if working yet, but thanks for this while it lasted.
If you get around to updating it great if not if was fun.

**Comment by DancingVixen** [comment]
How did you fix this? xd 

Thanks

**Comment by scoulomb** [comment]
Had same issue because had left a blank line at end of urls file
