### ISSUE TITLE
Unicode Encode Error

### ISSUE THREAD

**Issue by stefaneliu** [vitiko98/qobuz-dl#123]
Hey

Thank you for your job. But I have some issue when downloading an album with an astrophe in the album name.

The album link is: 
https://play.qobuz.com/album/mlpgy3cjclfwa

The result is:
```
Downloading: Ai Wo Hai Shi Ta (D\u2019MMGO Rel.)
Quality: FLAC (24/48)

Traceback (most recent call last):
  File "/usr/local/bin/qobuz-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/qobuz_dl/cli.py", line 176, in main
    _handle_commands(qobuz, arguments)
  File "/usr/local/lib/python3.9/dist-packages/qobuz_dl/cli.py", line 83, in _handle_commands
    qobuz.download_list_of_urls(arguments.SOURCE)
  File "/usr/local/lib/python3.9/dist-packages/qobuz_dl/core.py", line 180, in download_list_of_urls
    self.handle_url(url)
  File "/usr/local/lib/python3.9/dist-packages/qobuz_dl/core.py", line 160, in handle_url
    self.download_from_id(
  File "/usr/local/lib/python3.9/dist-packages/qobuz_dl/core.py", line 105, in download_from_id
    dloader.download_id_by_type(not album)
  File "/usr/local/lib/python3.9/dist-packages/qobuz_dl/downloader.py", line 61, in download_id_by_type
    self.download_release()
  File "/usr/local/lib/python3.9/dist-packages/qobuz_dl/downloader.py", line 102, in download_release
    os.makedirs(dirn, exist_ok=True)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 66: ordinal not in range(256)
```
What should I do to avoid this error?

Thank you.

**Comment by stefaneliu** [comment]
just install utf-8, and the problem is solved.
