### ISSUE TITLE
ERROR: Looks like the AppSecret is down again

### ISSUE THREAD

**Issue by Gamer4Life2020** [vitiko98/qobuz-dl#134]
Getting tokens. Please wait...
Config file updated. Edit more options in C:\Users\Admin\AppData\Roaming\qobuz-dl\config.ini
so you don't have to call custom flags every time you run a qobuz-dl command.
Logging...
Logged: OK
Membership: Studio
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\Scripts\qobuz-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\qobuz_dl\cli.py", line 174, in main
    qobuz.initialize_client(email, password, app_id, secrets)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\qobuz_dl\core.py", line 73, in initialize_client
    self.client = qopy.Client(email, pwd, app_id, secrets)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\qobuz_dl\qopy.py", line 39, in __init__
    self.cfg_setup()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\qobuz_dl\qopy.py", line 204, in cfg_setup
    raise InvalidAppSecretError("Invalid app secret.\n" + RESET)
qobuz_dl.exceptions.InvalidAppSecretError: Invalid app secret.
Reset your credentials with 'qobuz-dl -r'

**Comment by breadforall** [comment]
It's downloading just fine, uninstall and install it again.

**Comment by Gamer4Life2020** [comment]
Thanks, I have installed several but had to look how to uninstall. Working fine now.
