### ISSUE TITLE
parameters in sound quality

### ISSUE THREAD

**Issue by boistordu** [vitiko98/qobuz-dl#142]
not sure if it's already in the list of issues.
In the first interactive menu, for the quality of sound you've put as one of the choices "LOSSLESS".
Apparently it doesn't work: 
```
Traceback (most recent call last):
  File "/home/vigilian/.local/bin/qobuz-dl", line 8, in <module>
    sys.exit(main())
  File "/home/vigilian/.local/lib/python3.9/site-packages/qobuz_dl/cli.py", line 174, in main
    qobuz.initialize_client(email, password, app_id, secrets)
  File "/home/vigilian/.local/lib/python3.9/site-packages/qobuz_dl/core.py", line 74, in initialize_client
    logger.info(f"{YELLOW}Set max quality: {QUALITIES[int(self.quality)]}\n")
ValueError: invalid literal for int() with base 10: 'LOSSLESS'
```

I've had to decrease it to 20 to make it work. 32 was not good either.

**Comment by TheMelmacian** [comment]
The error message suggests that the quality was set to "LOSSLESS" literally. But the quality is number based:

-  5 = 320kbit/s
-  6 = LOSSLESS (CD quality)
-  7 = 24bit, up to 96kHz
- 27 = 24bit up to 192kHz

So for LOSSLESS the value must be set to 6
