### ISSUE TITLE
qobuz_dl.exceptions.AuthenticationError: Invalid credentials.

### ISSUE THREAD

**Issue by yogourts** [vitiko98/qobuz-dl#143]
C:\Users\Administrator>qobuz-dl dl https://play.qobuz.com/album/qxjbxh1dc3xyb -q 7
Logging...
Traceback (most recent call last):
  File "E:\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Python\Scripts\qobuz-dl.exe\__main__.py", line 7, in <module>
  File "E:\Python\lib\site-packages\qobuz_dl\cli.py", line 174, in main
    qobuz.initialize_client(email, password, app_id, secrets)
  File "E:\Python\lib\site-packages\qobuz_dl\core.py", line 73, in initialize_client
    self.client = qopy.Client(email, pwd, app_id, secrets)
  File "E:\Python\lib\site-packages\qobuz_dl\qopy.py", line 39, in __init__
    self.auth(email, pwd)
  File "E:\Python\lib\site-packages\qobuz_dl\qopy.py", line 124, in auth
    usr_info = self.api_call("user/login", email=email, pwd=pwd)
  File "E:\Python\lib\site-packages\qobuz_dl\qopy.py", line 109, in api_call
    raise AuthenticationError("Invalid credentials.\n" + RESET)
qobuz_dl.exceptions.AuthenticationError: Invalid credentials.
Reset your credentials with 'qobuz-dl -r'

**Comment by breadforall** [comment]
I'm having the same issue

**Comment by breadforall** [comment]
I had the same issue and fixed it by doing a full reinstall as well as resetting the credentials using the command 'qobuz-dl -r'
