### ISSUE TITLE
cannot get tokens after reset

### ISSUE THREAD

**Issue by Schnuffel12345** [vitiko98/qobuz-dl#150]
hello 
after i used the reset command
qobuz-dl -r
qobuz-dl no longer works :-(

when i want to creat a new cfg file 
i get this error message after 
download quality

Getting tokens. Please wait...
Traceback (most recent call last):
  File "C:\Programme2\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Programme2\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Programme2\python\Scripts\qobuz-dl.exe\__main__.py", line 7, in <module>
  File "C:\Programme2\python\lib\site-packages\qobuz_dl\cli.py", line 113, in main
    _initial_checks()
  File "C:\Programme2\python\lib\site-packages\qobuz_dl\cli.py", line 106, in _initial_checks
    _reset_config(CONFIG_FILE)
  File "C:\Programme2\python\lib\site-packages\qobuz_dl\cli.py", line 57, in _reset_config
    config["DEFAULT"]["app_id"] = str(spoofer.getAppId())
  File "C:\Programme2\python\lib\site-packages\qobuz_dl\spoofbuz.py", line 25, in getAppId
    return re.search(self.appId_regex, self.bundle).group("app_id")
AttributeError: 'NoneType' object has no attribute 'group'

 i reinstalled qobuz-dl but it didn't help

**Comment by blake961** [comment]
same here, went to reset this morning and got the same error.

**Comment by Lionelh2** [comment]
Same here. Tried to log in with another app and unable to log in.  Qobuz apps all work fine.

Seems like Qobuz API login procedure has changed.

**Comment by countthesaints** [comment]
It looks like a fix was found via [another](https://github.com/ImAiiR/QobuzDownloaderX/issues/116#issuecomment-1131959643) program, however I wouldn't know how to go about sorting this one out. I have sent the dev a message on last.fm—let's hope they see it.

**Comment by vitiko98** [comment]
I'm aware of the issue. Sadly, I don't have any Qobuz account available at the moment. I'm gonna try to get one ASAP so I can fix this.

**Comment by vitiko98** [comment]
It should be fixed. You can upgrade with `pip install --upgrade qobuz-dl`

Let me know if the issue persists

**Comment by Schnuffel12345** [comment]
hi Vitiko

thx for the fast fix
its working again :-)

and thx for your nice tool

**Comment by blake961** [comment]
thanks so much for the speedy fix!!
