### ISSUE TITLE
Fresh install, modulenotfound: No module named 'mutagen'

### ISSUE THREAD

**Issue by alphawave415** [vitiko98/qobuz-dl#151]
After installing pip, then running the QB-dl install script which appears to be successful, try to run qobuz-dl results in this error:
~$ qobuz-dl 
Traceback (most recent call last):
  File "/home/alphawave7/.local/bin/qobuz-dl", line 5, in <module>
    from qobuz_dl import main
  File "/home/alphawave7/.local/lib/python3.9/site-packages/qobuz_dl/__init__.py", line 2, in <module>
    from .cli import main
  File "/home/alphawave7/.local/lib/python3.9/site-packages/qobuz_dl/cli.py", line 11, in <module>
    from qobuz_dl.core import QobuzDL
  File "/home/alphawave7/.local/lib/python3.9/site-packages/qobuz_dl/core.py", line 10, in <module>
    from qobuz_dl import downloader, qopy
  File "/home/alphawave7/.local/lib/python3.9/site-packages/qobuz_dl/downloader.py", line 9, in <module>
    import qobuz_dl.metadata as metadata
  File "/home/alphawave7/.local/lib/python3.9/site-packages/qobuz_dl/metadata.py", line 5, in <module>
    from mutagen.flac import FLAC, Picture
ModuleNotFoundError: No module named 'mutagen'

Hoping for an easy fix! Cheers!

**Comment by vitiko98** [comment]
Fixed. Thanks for the report. 

You can run `pip install --upgrade qobuz-dl` to update the tool
