### ISSUE TITLE
Not able to download artist's discography

### ISSUE THREAD

**Issue by Burroughs7005** [vitiko98/qobuz-dl#157]
Hi, I can successfully download a single album, but I get an error if I try to download the whole discography:

`Logging...
Logged: OK
Membership: Studio
Traceback (most recent call last):
  File "/opt/homebrew/bin/qobuz-dl", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/qobuz_dl/cli.py", line 174, in main
    qobuz.initialize_client(email, password, app_id, secrets)
  File "/opt/homebrew/lib/python3.9/site-packages/qobuz_dl/core.py", line 74, in initialize_client
    logger.info(f"{YELLOW}Set max quality: {QUALITIES[int(self.quality)]}\n")
ValueError: invalid literal for int() with base 10: '24B'`

I'm using macOS Monterey 12.4.

**Comment by vitiko98** [comment]
What command did you use?

**Comment by Burroughs7005** [comment]
This is the executable: 
/opt/homebrew/bin/qobuz-dl

**Comment by vitiko98** [comment]
But what was the complete command? (eg. `qobuz-dl dl SOME_URL --some-flag`)
