### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'lower'

### ISSUE THREAD

**Issue by EmmaDuch** [vitiko98/qobuz-dl#159]
Today, I can no longer use the 'fun' option.
The 'url' option works.

Traceback (most recent call last):
  File "/home/manu/.local/bin/qobuz-dl", line 8, in <module>
    sys.exit(main())
  File "/home/manu/.local/lib/python3.10/site-packages/qobuz_dl/cli.py", line 176, in main
    _handle_commands(qobuz, arguments)
  File "/home/manu/.local/lib/python3.10/site-packages/qobuz_dl/cli.py", line 91, in _handle_commands
    qobuz.interactive()
  File "/home/manu/.local/lib/python3.10/site-packages/qobuz_dl/core.py", line 303, in interactive
    ].lower()
AttributeError: 'tuple' object has no attribute 'lower'

**Comment by rusdyshuka** [comment]
I also experienced the same thing when running the command qobuz-dl

![Screenshot_20220719-002011_Termux~2](https://user-images.githubusercontent.com/71666281/179567926-2bcaee9d-20d6-4381-bac2-623d2d6a2e50.png)

**Comment by rusdyshuka** [comment]
I also experienced the same thing when running the command qobuz-dl fun and qobuz-dl dl 

![Screenshot_20220719-003715_Termux~2](https://user-images.githubusercontent.com/71666281/179570635-a7a1f5dd-b695-49d7-9243-87dd1e37ada5.png)
![Screenshot_20220719-002011_Termux~2](https://user-images.githubusercontent.com/71666281/179570642-ee695137-2574-4af7-ab9a-1ea7aea2d555.png)

**Comment by rusdyshuka** [comment]
I experienced that too
![Screenshot_20220719-002011_Termux~2](https://user-images.githubusercontent.com/71666281/179571731-f9d565a0-e335-4474-befc-d21455eb321b.png)

**Comment by alex-got-ears** [comment]
same issue with fun and lucky mode. 
(Linux 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64)

Logging...
Logged: OK
Membership: Studio
Set max quality: 27 - 24 bit, >96kHz

Ok, we'll search for albums
Enter your search: [Ctrl + c to quit]
- otis
Searching...
Traceback (most recent call last):
  File "/usr/local/bin/qobuz-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/qobuz_dl/cli.py", line 176, in main
    _handle_commands(qobuz, arguments)
  File "/usr/local/lib/python3.9/dist-packages/qobuz_dl/cli.py", line 91, in _handle_commands
    qobuz.interactive()
  File "/usr/local/lib/python3.9/dist-packages/qobuz_dl/core.py", line 323, in interactive
    selected_items = pick(
TypeError: pick() got an unexpected keyword argument 'options_map_func'

would be great, if you can fix it.
