### ISSUE TITLE
configparser.InterpolationSyntaxError

### ISSUE THREAD

**Issue by mbfrankz** [vitiko98/qobuz-dl#16]
Getting the error below trying to enter my password or update my config using -r.  Related I'm assuming to a % in my PW.

```
Traceback (most recent call last):

  File "\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)

  File "\runpy.py", line 85, in _run_code
    exec(code, run_globals)

  File "\Scripts\qobuz-dl.exe\__main__.py", line 9, in <module>

  File "\site-packages\qobuz_dl\cli.py", line 255, in main
    password = config["DEFAULT"]["password"]

  File "\configparser.py", line 1252, in __getitem__
    return self._parser.get(self._name, key)

  File "\configparser.py", line 799, in get
    d)

  File "\configparser.py", line 394, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)

 File "\configparser.py", line 444, in _interpolate_some
    "found: %r" % (rest,))

configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: [PW redacted]`
```
Older version (before the .exe) worked fine.

**Comment by vitiko98** [comment]
Thanks for reporting this. It'll be fixed in the next hours.

**Comment by vitiko98** [comment]
It should be fixed now. Please test it.

**Comment by mbfrankz** [comment]
Worked like a charm.  Thanks.
