### ISSUE TITLE
Not all albums have version

### ISSUE THREAD

**Issue by steve-o-matic** [vitiko98/qobuz-dl#17]
Example: https://play.qobuz.com/album/0002894814756

Works with older version of this package but after merging the pull requests results in error.

Probably just needs another Try/Catch block in the code.

**Comment by steve-o-matic** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/qobuz-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/qobuz_dl/cli.py", line 288, in main
    interactive(
  File "/usr/local/lib/python3.9/site-packages/qobuz_dl/cli.py", line 168, in interactive
    processSelected(Qz, path, Albums, IDs, Types, quality, embed_art)
  File "/usr/local/lib/python3.9/site-packages/qobuz_dl/cli.py", line 76, in processSelected
    downloader.download_id_by_type(
  File "/usr/local/lib/python3.9/site-packages/qobuz_dl/downloader.py", line 139, in download_id_by_type
    if meta["version"]
KeyError: 'version'

**Comment by vitiko98** [comment]
Thanks for the report.
