### ISSUE TITLE
Error while searching for classical music in interactive mode

### ISSUE THREAD

**Issue by steve-o-matic** [vitiko98/qobuz-dl#19]
In 'fun' mode, a search for a composer e.g. Handel will result in an error around the performer field.
Again, support for this field and storing that in the ID3 would be amazing. 

Thanks for your great work!

Steve

**Comment by vitiko98** [comment]
Thanks for the report, Steve.

Would you mind posting the error output?

**Comment by steve-o-matic** [comment]
I can't reproduce this now with the current version. Will close and document it better if it happens again. In previous version it looked like:

Searching...
Traceback (most recent call last):
  File "/qobuz-dl/qo_utils/search.py", line 23, in itResults
    i["artist"]["name"],
KeyError: 'artist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/qobuz-dl/main.py", line 156, in <module>
    sys.exit(main())
  File "/qobuz-dl/main.py", line 150, in main
    interactive(Qz, directory, arguments.l, not arguments.a)
  File "/qobuz-dl/main.py", line 114, in interactive
    start.getResults(tracks)
  File "/qobuz-dl/qo_utils/search.py", line 43, in getResults
    self.itResults(self.Tracks)
  File "/qobuz-dl/qo_utils/search.py", line 32, in itResults
    i["performer"]["name"],
KeyError: 'performer'
