### ISSUE TITLE
Unable to download even after reinstall and recreate of ini file

### ISSUE THREAD

**Issue by nwpsys** [vitiko98/qobuz-dl#191]
Here is the error - means little to me, I'm afraid. I have used it successfully last back on 16th January.

C:\Users\Nige>qobuz-dl dl https://play.qobuz.com/album/jmuaw5w8ny2vb
Logging...
Logged: OK
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Nige\AppData\Local\Programs\Python\Python311\Scripts\qobuz-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\Nige\AppData\Local\Programs\Python\Python311\Lib\site-packages\qobuz_dl\cli.py", line 174, in main
    qobuz.initialize_client(email, password, app_id, secrets)
  File "C:\Users\Nige\AppData\Local\Programs\Python\Python311\Lib\site-packages\qobuz_dl\core.py", line 73, in initialize_client
    self.client = qopy.Client(email, pwd, app_id, secrets)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nige\AppData\Local\Programs\Python\Python311\Lib\site-packages\qobuz_dl\qopy.py", line 39, in __init__
    self.auth(email, pwd)
  File "C:\Users\Nige\AppData\Local\Programs\Python\Python311\Lib\site-packages\qobuz_dl\qopy.py", line 124, in auth
    usr_info = self.api_call("user/login", email=email, pwd=pwd)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nige\AppData\Local\Programs\Python\Python311\Lib\site-packages\qobuz_dl\qopy.py", line 120, in api_call
    r.raise_for_status()
  File "C:\Users\Nige\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.qobuz.com/api.json/0.2/user/login?email=nwpsys%40gmail.com&password=a47d4e54e53339b57c7e429dec72760f&app_id=814460817

Thanks for any help.

**Comment by nwpsys** [comment]
Hmmm - seems to be just that release so not sure if it is worth looking into ?

**Comment by nwpsys** [comment]
Grrrr - it worked for one album and now I have the same error. when I try a second. Is it me doing something wrong ?

**Comment by nwpsys** [comment]
The error was my VPN. Split Tunneling is implemented pretty poorly !
