### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by thisisawesome1994** [vitiko98/qobuz-dl#194]
I get this error on all tried downloads.
Is there something I can do?
I tried resetting the config for new token, but that didnt help.

I will try reinstall qobuz-dl and python soon.

Is there anything I can do?

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python311\Scripts\qobuz-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python311\Lib\site-packages\qobuz_dl\cli.py", line 176, in main
    _handle_commands(qobuz, arguments)
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python311\Lib\site-packages\qobuz_dl\cli.py", line 83, in _handle_commands
    qobuz.download_list_of_urls(arguments.SOURCE)
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python311\Lib\site-packages\qobuz_dl\core.py", line 180, in download_list_of_urls
    self.handle_url(url)
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python311\Lib\site-packages\qobuz_dl\core.py", line 128, in handle_url
    url_type, item_id = get_url_info(url)
                        ^^^^^^^^^^^^^^^^^
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python311\Lib\site-packages\qobuz_dl\utils.py", line 190, in get_url_info
    return r.groups()
           ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'groups'
Logging...
Logged: OK

**Comment by archibaldodlc** [comment]
I have the same problem with Joy Division discography.

**Comment by archibaldodlc** [comment]
Hi, @thisisawesome1994. Thanks for the tips. This happens to me only with Joy Division discography, the other downloads I tried work fine. I tried yesterday and today with the same behavior, so I think it is related to the files, maybe an illegible character or some tag information not provided by Qobuz, or something else, I don't know.

**Comment by AltGr** [comment]
Just had this issue, which got fixed by removing `qobuz_dl.db` (inside the config directory, `~/.config/qobuz-dl` in my case)
