### ISSUE TITLE
Can't run qobuz-dl after windows reinstall

### ISSUE THREAD

**Issue by expatoz** [vitiko98/qobuz-dl#203]
Hi after a fresh install of windows 10, i can't run the qobuz-dl.exe command, i have installed python latest version and my email/pass are correct, i am getting this error
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python311\Scripts\qobuz-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python311\Lib\site-packages\qobuz_dl\cli.py", line 113, in main
    _initial_checks()
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python311\Lib\site-packages\qobuz_dl\cli.py", line 106, in _initial_checks
    _reset_config(CONFIG_FILE)
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python311\Lib\site-packages\qobuz_dl\cli.py", line 57, in _reset_config
    config["DEFAULT"]["app_id"] = str(bundle.get_app_id())
                                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python311\Lib\site-packages\qobuz_dl\bundle.py", line 53, in get_app_id
    raise NotImplementedError("Failed to match APP ID")
NotImplementedError: Failed to match APP ID

i don't have any idea how to correct this or what mistake i amm making
thanks

**Comment by vitiko98** [comment]
#204
