### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by galaxynite** [vitiko98/qobuz-dl#21]
when searching "David Ian"

**Comment by vitiko98** [comment]
Post the output

**Comment by galaxynite** [comment]
Logging...
Logged: OK
Membership: Studio

Enter your search: [Ctrl + c to quit]
- David Ian
Searching...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/qobuz_dl/search.py", line 23, in itResults
    i["artist"]["name"],
KeyError: 'artist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/qobuz-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/qobuz_dl/cli.py", line 226, in main
    interactive(Qz, directory, arguments.l, not arguments.a)
  File "/usr/local/lib/python3.8/site-packages/qobuz_dl/cli.py", line 151, in interactive
    start.getResults(tracks)
  File "/usr/local/lib/python3.8/site-packages/qobuz_dl/search.py", line 43, in getResults
    self.itResults(self.Tracks)
  File "/usr/local/lib/python3.8/site-packages/qobuz_dl/search.py", line 32, in itResults
    i["performer"]["name"],
KeyError: 'performer'

**Comment by steve-o-matic** [comment]
This looks a lot like what I was talking about in: #19 but it is not always reproducible.
