### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by massimocorso77** [vitiko98/qobuz-dl#251]
Logging...
Logged: OK
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\m.corso\AppData\Local\Programs\Python\Python311\Scripts\qobuz-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\m.corso\AppData\Local\Programs\Python\Python311\Lib\site-packages\qobuz_dl\cli.py", line 174, in main
    qobuz.initialize_client(email, password, app_id, secrets)
  File "C:\Users\m.corso\AppData\Local\Programs\Python\Python311\Lib\site-packages\qobuz_dl\core.py", line 73, in initialize_client
    self.client = qopy.Client(email, pwd, app_id, secrets)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.corso\AppData\Local\Programs\Python\Python311\Lib\site-packages\qobuz_dl\qopy.py", line 39, in __init__
    self.auth(email, pwd)
  File "C:\Users\m.corso\AppData\Local\Programs\Python\Python311\Lib\site-packages\qobuz_dl\qopy.py", line 124, in auth
    usr_info = self.api_call("user/login", email=email, pwd=pwd)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m.corso\AppData\Local\Programs\Python\Python311\Lib\site-packages\qobuz_dl\qopy.py", line 120, in api_call
    r.raise_for_status()
  File "C:\Users\m.corso\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://www.qobuz.com/api.json/0.2/user/login?email=massimo.corso%40gmail.com&password=fdas832uen12j1j07&app_id=950096963

**Comment by massimocorso77** [comment]
Non all workshop fine
