### ISSUE TITLE
There are a lot of errors like that!

### ISSUE THREAD

**Issue by fominator** [vitiko98/qobuz-dl#264]
Traceback (most recent call last):
  File "/usr/local/bin/qobuz-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/qobuz_dl/cli.py", line 176, in main
    _handle_commands(qobuz, arguments)
  File "/usr/local/lib/python3.10/dist-packages/qobuz_dl/cli.py", line 83, in _handle_commands
    qobuz.download_list_of_urls(arguments.SOURCE)
  File "/usr/local/lib/python3.10/dist-packages/qobuz_dl/core.py", line 180, in download_list_of_urls
    self.handle_url(url)
  File "/usr/local/lib/python3.10/dist-packages/qobuz_dl/core.py", line 168, in handle_url
    self.download_from_id(item_id, type_dict["album"])
  File "/usr/local/lib/python3.10/dist-packages/qobuz_dl/core.py", line 105, in download_from_id
    dloader.download_id_by_type(not album)
  File "/usr/local/lib/python3.10/dist-packages/qobuz_dl/downloader.py", line 61, in download_id_by_type
    self.download_release()
  File "/usr/local/lib/python3.10/dist-packages/qobuz_dl/downloader.py", line 120, in download_release
    self._download_and_tag(
  File "/usr/local/lib/python3.10/dist-packages/qobuz_dl/downloader.py", line 225, in _download_and_tag
    tqdm_download(url, filename, filename)
  File "/usr/local/lib/python3.10/dist-packages/qobuz_dl/downloader.py", line 327, in tqdm_download
    raise ConnectionError("File download was interrupted for " + fname)
ConnectionError: File download was interrupted for Qobuz Downloads/John Coltrane - Blue Train The Complete Masters (1958) [24-96]/Disc 2/.06.tmp

**Comment by fominator** [comment]
And speed drop to zero very often as well! Also connection interrupt messages.

**Comment by fominator** [comment]
Error getting release: ('Connection broken: IncompleteRead(12089172 bytes read, 167299377 more expected)', IncompleteRead(12089172 bytes read, 167299377 more expected)). Skipping...
