### ISSUE TITLE
Unicode Error while downloading, character '\xf3' 

### ISSUE THREAD

**Issue by PetrPetrov00** [vitiko98/qobuz-dl#267]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Scripts\qobuz-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\qobuz_dl\cli.py", line 176, in main
    _handle_commands(qobuz, arguments)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\qobuz_dl\cli.py", line 83, in _handle_commands
    qobuz.download_list_of_urls(arguments.SOURCE)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\qobuz_dl\core.py", line 180, in download_list_of_urls
    self.handle_url(url)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\qobuz_dl\core.py", line 166, in handle_url
    make_m3u(new_path)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\qobuz_dl\utils.py", line 73, in make_m3u
    pl.write("\n\n".join(track_list))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\xf3' in position 5319: character maps to <undefined>

**Comment by VoidSpectrum** [comment]
I'm getting a similar error, but mine is multiple characters, its happened at the end of the list of songs in a 360 song playlist, but looking at what it finished with, im missing around ~20 songs.
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Andre\scoop\apps\python\current\Scripts\qobuz-dl.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\Andre\scoop\apps\python\current\Lib\site-packages\qobuz_dl\cli.py", line 176, in main
    _handle_commands(qobuz, arguments)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andre\scoop\apps\python\current\Lib\site-packages\qobuz_dl\cli.py", line 83, in _handle_commands
    qobuz.download_list_of_urls(arguments.SOURCE)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andre\scoop\apps\python\current\Lib\site-packages\qobuz_dl\core.py", line 180, in download_list_of_urls
    self.handle_url(url)
    ~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Andre\scoop\apps\python\current\Lib\site-packages\qobuz_dl\core.py", line 166, in handle_url
    make_m3u(new_path)
    ~~~~~~~~^^^^^^^^^^
  File "C:\Users\Andre\scoop\apps\python\current\Lib\site-packages\qobuz_dl\utils.py", line 73, in make_m3u
    pl.write("\n\n".join(track_list))
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andre\scoop\apps\python\current\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 4917-4921: character maps to <undefined>
```

**Comment by u12bdragon** [comment]
same
