### ISSUE TITLE
after reset the pc windows 10 qobuz dl is not working, I did qobuz-dl -r write user id password again it is not working again

### ISSUE THREAD

**Issue by jimmyra62** [vitiko98/qobuz-dl#268]
C:\Users\bobby>qobuz-dl dl https://play.qobuz.com/album/ns4nn3x1gfddb
Logging...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\bobby\AppData\Local\Programs\Python\Python312\Scripts\qobuz-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\bobby\AppData\Local\Programs\Python\Python312\Lib\site-packages\qobuz_dl\cli.py", line 174, in main
    qobuz.initialize_client(email, password, app_id, secrets)
  File "C:\Users\bobby\AppData\Local\Programs\Python\Python312\Lib\site-packages\qobuz_dl\core.py", line 73, in initialize_client
    self.client = qopy.Client(email, pwd, app_id, secrets)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bobby\AppData\Local\Programs\Python\Python312\Lib\site-packages\qobuz_dl\qopy.py", line 39, in __init__
    self.auth(email, pwd)
  File "C:\Users\bobby\AppData\Local\Programs\Python\Python312\Lib\site-packages\qobuz_dl\qopy.py", line 124, in auth
    usr_info = self.api_call("user/login", email=email, pwd=pwd)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bobby\AppData\Local\Programs\Python\Python312\Lib\site-packages\qobuz_dl\qopy.py", line 109, in api_call
    raise AuthenticationError("Invalid credentials.\n" + RESET)
qobuz_dl.exceptions.AuthenticationError: Invalid credentials.
Reset your credentials with 'qobuz-dl -r'

**Comment by bhalejos** [comment]
Did you ever get any answer on this? I've started getting the same error today.
