### ISSUE TITLE
Fail gracefully when qobuz fails

### ISSUE THREAD

**Issue by steve-o-matic** [vitiko98/qobuz-dl#32]
Traceback (most recent call last):
  File "/.local/bin/qobuz-dl", line 10, in <module>
    sys.exit(main())
  File "/.local/lib/python3.9/site-packages/qobuz_dl/cli.py", line 101, in main
    qobuz.interactive()
  File "/.local/lib/python3.9/site-packages/qobuz_dl/core.py", line 322, in interactive
    self.download_list_of_urls(final_url_list)
  File "/.local/lib/python3.9/site-packages/qobuz_dl/core.py", line 152, in download_list_of_urls
    self.handle_url(url)
  File "/.local/lib/python3.9/site-packages/qobuz_dl/core.py", line 137, in handle_url
    new_path,
  File "/.local/lib/python3.9/site-packages/qobuz_dl/core.py", line 91, in download_from_id
    self.ignore_singles_eps,
  File "/.local/lib/python3.9/site-packages/qobuz_dl/downloader.py", line 227, in download_id_by_type
    meta = client.get_track_meta(item_id)
  File "/.local/lib/python3.9/site-packages/qobuz_dl/qopy.py", line 140, in get_track_meta
    return self.api_call("track/get", id=id)
  File "/.local/lib/python3.9/site-packages/qobuz_dl/qopy.py", line 108, in api_call
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.qobuz.com/api.json/0.2/track/get?track_id=49129481

**Comment by steve-o-matic** [comment]
Yes, very consistently.

**Comment by steve-o-matic** [comment]
It is part of a large playlist. I will try to come up with a minimal example and send to you.

**Comment by steve-o-matic** [comment]
Playlist: Trojan Records Ska, Reggae, Rocksteady (and a few odds 'n ends)
Song after I Am Coming Home
I don't think it downloads things in order.

**Comment by vitiko98** [comment]
> Playlist: Trojan Records Ska, Reggae, Rocksteady (and a few odds 'n ends)
> Song after I Am Coming Home

I'll try

> I don't think it downloads things in order.

I suppose that's a file manager issue. `qobuz-dl` downloads from the list that Qobuz returns. There's no way to alter that order. :p
