### ISSUE TITLE
Can't download tracks with special characters.

### ISSUE THREAD

**Issue by bydioeds** [vitiko98/qobuz-dl#33]
When i try to download tracks that have special characters e.g: Ö or japanese characters, it throws this error
```python
Traceback (most recent call last):
  File "/crypt/archive/music/qobuz-dl/venvdocker/bin/qobuz-dl", line 11, in <module>
    sys.exit(main())
  File "/crypt/archive/music/qobuz-dl/venvdocker/lib/python3.6/site-packages/qobuz_dl/cli.py", line 93, in main
    qobuz.download_list_of_urls(arguments.SOURCE)
  File "/crypt/archive/music/qobuz-dl/venvdocker/lib/python3.6/site-packages/qobuz_dl/core.py", line 152, in download_list_of_urls
    self.handle_url(url)
  File "/crypt/archive/music/qobuz-dl/venvdocker/lib/python3.6/site-packages/qobuz_dl/core.py", line 140, in handle_url
    self.download_from_id(item_id, type_dict["album"])
  File "/crypt/archive/music/qobuz-dl/venvdocker/lib/python3.6/site-packages/qobuz_dl/core.py", line 91, in download_from_id
    self.ignore_singles_eps,
  File "/crypt/archive/music/qobuz-dl/venvdocker/lib/python3.6/site-packages/qobuz_dl/downloader.py", line 229, in download_id_by_type
    print("\nDownloading: {}\n".format(track_title))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-17: ordinal not in range(128)

```

I'm using the latest version.

**Comment by vitiko98** [comment]
What album is?

**Comment by bydioeds** [comment]
> What album is?

I was trying to download the artist [ `Ghost B.C.`](https://play.qobuz.com/artist/1036816) and the album is [Meliora](https://play.qobuz.com/album/e9133hdpsnbac)

**Comment by bydioeds** [comment]
@vitiko98 I'm deeply sorry it was an issue on my part, i forgot i was running it on a docker container, but basically i wasn't setting utf-8 as the language of the image it was fixed doing this
```
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
```
again sorry for wasting your time

**Comment by vitiko98** [comment]
Np. Enjoy!
