### ISSUE TITLE
'Client' object has no attribute 'sec'

### ISSUE THREAD

**Issue by steve-o-matic** [vitiko98/qobuz-dl#39]
Downloading all the music from '80s Synth-Pop (playlist)!
50 downloads in queue
Traceback (most recent call last):
  File "/usr/local/bin/qobuz-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/qobuz_dl/cli.py", line 116, in main
    qobuz.interactive()
  File "/usr/local/lib/python3.9/site-packages/qobuz_dl/core.py", line 337, in interactive
    self.download_list_of_urls(final_url_list)
  File "/usr/local/lib/python3.9/site-packages/qobuz_dl/core.py", line 169, in download_list_of_urls
    self.handle_url(url)
  File "/usr/local/lib/python3.9/site-packages/qobuz_dl/core.py", line 149, in handle_url
    self.download_from_id(
  File "/usr/local/lib/python3.9/site-packages/qobuz_dl/core.py", line 99, in download_from_id
    downloader.download_id_by_type(
  File "/usr/local/lib/python3.9/site-packages/qobuz_dl/downloader.py", line 254, in download_id_by_type
    parse = client.get_track_url(item_id, quality)
  File "/usr/local/lib/python3.9/site-packages/qobuz_dl/qopy.py", line 149, in get_track_url
    return self.api_call("track/getFileUrl", id=id, fmt_id=fmt_id)
  File "/usr/local/lib/python3.9/site-packages/qobuz_dl/qopy.py", line 91, in api_call
    fmt_id, track_id, unix, self.sec
AttributeError: 'Client' object has no attribute 'sec'

**Comment by vitiko98** [comment]
Can you reproduce?

**Comment by vitiko98** [comment]
Two scenarios:

1. You need to reset your config file
2. You are making too much requests in a short period of time

I've added an exception message to notify this.
