### ISSUE TITLE
doesn't work anymore

### ISSUE THREAD

**Issue by Aminizm** [vitiko98/qobuz-dl#48]
I've just updated qobuz-dl to the last release and it's now crashing, please see below
apologies if obvious but I have no clue
thanks

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/qobuz-dl", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qobuz_dl/cli.py", line 92, in main
    password = base64.b64decode(config["DEFAULT"]["password"]).decode()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (9) cannot be 1 more than a multiple of 4

**Comment by Aminizm** [comment]
qobuz-dl-0.4.2 working well 
the error is with qobuz-dl-0.9.0

**Comment by vitiko98** [comment]
It should be fixed now.

**Comment by Aminizm** [comment]
yes thanks!
the new release is just amazing! thank you!
