### ISSUE TITLE
Same following errors occurs several times since updated to latest version

### ISSUE THREAD

**Issue by iamhongliang** [vitiko98/qobuz-dl#49]
Hi ,the following errors information shows several times on different albums downloading :

eg: https://play.qobuz.com/album/0002894743832

Traceback (most recent call last):
  File "/usr/local/bin/qobuz-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/qobuz_dl/cli.py", line 139, in main
    qobuz.download_list_of_urls(arguments.SOURCE)
  File "/usr/local/lib/python3.9/site-packages/qobuz_dl/core.py", line 180, in download_list_of_urls
    self.download_from_txt_file(url)
  File "/usr/local/lib/python3.9/site-packages/qobuz_dl/core.py", line 199, in download_from_txt_file
    self.download_list_of_urls(urls)
  File "/usr/local/lib/python3.9/site-packages/qobuz_dl/core.py", line 182, in download_list_of_urls
    self.handle_url(url)
  File "/usr/local/lib/python3.9/site-packages/qobuz_dl/core.py", line 170, in handle_url
    self.download_from_id(item_id, type_dict["album"])
  File "/usr/local/lib/python3.9/site-packages/qobuz_dl/core.py", line 108, in download_from_id
    downloader.download_id_by_type(
  File "/usr/local/lib/python3.9/site-packages/qobuz_dl/downloader.py", line 248, in download_id_by_type
    download_and_tag(
  File "/usr/local/lib/python3.9/site-packages/qobuz_dl/downloader.py", line 146, in download_and_tag
    f'{artist if artist else track_metadata["album"]["artist"]["name"]}'
KeyError: 'album'

**Comment by vitiko98** [comment]
Done
