### ISSUE TITLE
This release is not streamable

### ISSUE THREAD

**Issue by zozzza** [vitiko98/qobuz-dl#60]
```
Traceback (most recent call last):
  File "/home/user/.local/bin/qobuz-dl", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/qobuz_dl/cli.py", line 139, in main
    qobuz.download_list_of_urls(arguments.SOURCE)
  File "/home/user/.local/lib/python3.8/site-packages/qobuz_dl/core.py", line 186, in download_list_of_urls
    self.handle_url(url)
  File "/home/user/.local/lib/python3.8/site-packages/qobuz_dl/core.py", line 174, in handle_url
    self.download_from_id(item_id, type_dict["album"])
  File "/home/user/.local/lib/python3.8/site-packages/qobuz_dl/core.py", line 112, in download_from_id
    downloader.download_id_by_type(
  File "/home/user/.local/lib/python3.8/site-packages/qobuz_dl/downloader.py", line 205, in download_id_by_type
    raise NonStreamable("This release is not streamable")
qobuz_dl.exceptions.NonStreamable: This release is not streamable

```
Due to the recent qobuz changes.

**Comment by vitiko98** [comment]
Thanks for reporting!
