### ISSUE TITLE
not log

### ISSUE THREAD

**Issue by linealgiaydep** [vitiko98/qobuz-dl#61]
Traceback (most recent call last):
  File "/home/user/.local/bin/qobuz-dl", line 7, in <module>
    from qobuz_dl import main
  File "/home/user/.local/lib/python3.5/site-packages/qobuz_dl/__init__.py", line 1, in <module>
    from .qopy import Client
  File "/home/user/.local/lib/python3.5/site-packages/qobuz_dl/qopy.py", line 27
    logger.info(f"{YELLOW}Logging...")
                                    ^
SyntaxError: invalid syntax

Pls help me
I run on seedbox and colab

**Comment by vitiko98** [comment]
You need to update your Python version to 3.6 or more.
