### ISSUE TITLE
Invalid app secret

### ISSUE THREAD

**Issue by Aminizm** [vitiko98/qobuz-dl#65]
have reset credentials but same below error message

Logged: OK
Membership: Studio
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/qobuz-dl", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qobuz_dl/cli.py", line 135, in main
    qobuz.initialize_client(email, password, app_id, secrets)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qobuz_dl/core.py", line 81, in initialize_client
    self.client = qopy.Client(email, pwd, app_id, secrets)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qobuz_dl/qopy.py", line 39, in __init__
    self.cfg_setup()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qobuz_dl/qopy.py", line 203, in cfg_setup
    raise InvalidAppSecretError("Invalid app secret.\n" + RESET)
qobuz_dl.exceptions.InvalidAppSecretError: Invalid app secret.
Reset your credentials with 'qobuz-dl -r'

**Comment by Aminizm** [comment]
restart of terminal made the trick
