### ISSUE TITLE
SSLError when trying to download from a list of links.

### ISSUE THREAD

**Issue by CyberLykan** [vitiko98/qobuz-dl#71]
```Python
Traceback (most recent call last):
  File "d:\programdata\miniconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\programdata\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\Miniconda3\Scripts\qobuz-dl.exe\__main__.py", line 7, in <module>
  File "d:\programdata\miniconda3\lib\site-packages\qobuz_dl\cli.py", line 139, in main
    qobuz.download_list_of_urls(arguments.SOURCE)
  File "d:\programdata\miniconda3\lib\site-packages\qobuz_dl\core.py", line 185, in download_list_of_urls
    self.download_from_txt_file(url)
  File "d:\programdata\miniconda3\lib\site-packages\qobuz_dl\core.py", line 204, in download_from_txt_file
    self.download_list_of_urls(urls)
  File "d:\programdata\miniconda3\lib\site-packages\qobuz_dl\core.py", line 187, in download_list_of_urls
    self.handle_url(url)
  File "d:\programdata\miniconda3\lib\site-packages\qobuz_dl\core.py", line 175, in handle_url
    self.download_from_id(item_id, type_dict["album"])
  File "d:\programdata\miniconda3\lib\site-packages\qobuz_dl\core.py", line 113, in download_from_id
    downloader.download_id_by_type(
  File "d:\programdata\miniconda3\lib\site-packages\qobuz_dl\downloader.py", line 249, in download_id_by_type
    download_and_tag(
  File "d:\programdata\miniconda3\lib\site-packages\qobuz_dl\downloader.py", line 157, in download_and_tag
    tqdm_download(url, filename, desc)
  File "d:\programdata\miniconda3\lib\site-packages\qobuz_dl\downloader.py", line 27, in tqdm_download
    for data in r.iter_content(chunk_size=1024):
  File "d:\programdata\miniconda3\lib\site-packages\requests\models.py", line 751, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "d:\programdata\miniconda3\lib\site-packages\urllib3\response.py", line 575, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "d:\programdata\miniconda3\lib\site-packages\urllib3\response.py", line 518, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "d:\programdata\miniconda3\lib\http\client.py", line 458, in read
    n = self.readinto(b)
  File "d:\programdata\miniconda3\lib\http\client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "d:\programdata\miniconda3\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "d:\programdata\miniconda3\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "d:\programdata\miniconda3\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2622)
```

**Comment by CyberLykan** [comment]
It's possible that I just screwed up something in my conda installation somehow, so I just reinstalled everything.

Closing unless the problem comes back.

**Comment by vitiko98** [comment]
Which release?

**Comment by CyberLykan** [comment]
Nevermind, I fixed it with this tool.
https://www.rizonesoft.com/downloads/complete-internet-repair/
