### ISSUE TITLE
Invalid app secret.

### ISSUE THREAD

**Issue by zozzza** [vitiko98/qobuz-dl#79]
@vitiko98 @nathom
The "classic" authorization error again. It is probably due to a recent qobuz security login changes. 
I ask the developers/users for confirmation. 
```
Traceback (most recent call last):
  File "/home/user/.local/bin/qobuz-dl", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/qobuz_dl/cli.py", line 135, in main
    qobuz.initialize_client(email, password, app_id, secrets)
  File "/home/user/.local/lib/python3.8/site-packages/qobuz_dl/core.py", line 81, in initialize_client
    self.client = qopy.Client(email, pwd, app_id, secrets)
  File "/home/user/.local/lib/python3.8/site-packages/qobuz_dl/qopy.py", line 39, in __init__
    self.cfg_setup()
  File "/home/user/.local/lib/python3.8/site-packages/qobuz_dl/qopy.py", line 203, in cfg_setup
    raise InvalidAppSecretError("Invalid app secret.\n" + RESET)
qobuz_dl.exceptions.InvalidAppSecretError: Invalid app secret.
Reset your credentials with 'qobuz-dl -r'

```

**Comment by nathom** [comment]
I had that issue last night too. I believe it works now though.

**Comment by zozzza** [comment]
@nathom 
You're right. Do you know why this sometimes happens?
