### ISSUE TITLE
KeyError: 'album'

### ISSUE THREAD

**Issue by CyberLykan** [vitiko98/qobuz-dl#84]
Traceback (most recent call last):
  File "d:\programdata\miniconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\programdata\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\Miniconda3\Scripts\qobuz-dl.exe\__main__.py", line 7, in <module>
  File "d:\programdata\miniconda3\lib\site-packages\qobuz_dl\cli.py", line 166, in main
    qobuz.download_list_of_urls(arguments.SOURCE)
  File "d:\programdata\miniconda3\lib\site-packages\qobuz_dl\core.py", line 223, in download_list_of_urls
    self.handle_url(url)
  File "d:\programdata\miniconda3\lib\site-packages\qobuz_dl\core.py", line 211, in handle_url
    self.download_from_id(item_id, type_dict["album"])
  File "d:\programdata\miniconda3\lib\site-packages\qobuz_dl\core.py", line 135, in download_from_id
    downloader.download_id_by_type(
  File "d:\programdata\miniconda3\lib\site-packages\qobuz_dl\downloader.py", line 327, in download_id_by_type
    sanitized_title = sanitize_filename(folder_format.format(**track_attr))
KeyError: 'album'

**Comment by CyberLykan** [comment]
Tested with this link: https://open.qobuz.com/track/104171464

**Comment by CyberLykan** [comment]
Works great now. Thank you!
(As of this writing, it has not been pushed to pypi yet.)

**Comment by CyberLykan** [comment]
Works great now. Thank you!
(As of this writing, it has not been pushed to pip yet.)
