### ISSUE TITLE
[BUG] Unable to start qobuz-dl in colab

### ISSUE THREAD

**Issue by Identivezz** [vitiko98/qobuz-dl#86]
using qobuz-dl in google colab i am getting this error:

Traceback (most recent call last):
  File "/usr/local/bin/qobuz-dl", line 5, in <module>
    from qobuz_dl import main
  File "/usr/local/lib/python3.7/dist-packages/qobuz_dl/__init__.py", line 2, in <module>
    from .cli import main
  File "/usr/local/lib/python3.7/dist-packages/qobuz_dl/cli.py", line 11, in <module>
    from qobuz_dl.core import QobuzDL
  File "/usr/local/lib/python3.7/dist-packages/qobuz_dl/core.py", line 542
    if (t := essence(item["title"])) not in title_grouped:
          ^
SyntaxError: invalid syntax

**Comment by magostinelli** [comment]
I have the same error on my Armbian 21.02.3 Buster

**Comment by zozzza** [comment]
@Identivezz @magostinelli 
Run with python3.9.

**Comment by magostinelli** [comment]
I don't havee python 3.9.

What do you think to run it in a docket container?

**Comment by vitiko98** [comment]
It should work now.
