### ISSUE TITLE
400 Client Error

### ISSUE THREAD

**Issue by zozzza** [vitiko98/qobuz-dl#87]
@nathom @vitiko98 
Error from qobuz API when trying to download an entire label by inserting the link taken from the qobuz store e.g.:`https://www.qobuz.com/us-en/label/rhino/download-streaming-albums/7425`

```
Traceback (most recent call last):
  File "/home/~/.local/bin/qobuz-dl", line 8, in <module>
    sys.exit(main())
  File "/home/~/.local/lib/python3.8/site-packages/qobuz_dl/cli.py", line 166, in main
    qobuz.download_list_of_urls(arguments.SOURCE)
  File "/home/~/.local/lib/python3.8/site-packages/qobuz_dl/core.py", line 223, in download_list_of_urls
    self.handle_url(url)
  File "/home/~/.local/lib/python3.8/site-packages/qobuz_dl/core.py", line 179, in handle_url
    content = [item for item in type_dict["func"](item_id)]
  File "/home/~/.local/lib/python3.8/site-packages/qobuz_dl/core.py", line 179, in <listcomp>
    content = [item for item in type_dict["func"](item_id)]
  File "/home/~/.local/lib/python3.8/site-packages/qobuz_dl/qopy.py", line 133, in multi_meta
    j = self.api_call(epoint, id=id, offset=offset, type=type)
  File "/home/~/.local/lib/python3.8/site-packages/qobuz_dl/qopy.py", line 114, in api_call
    r.raise_for_status()
  File "/home/~/.local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.qobuz.com/api.json/0.2/label/get?label_id=download&limit=500&offset=0&extra=albums

```

**Comment by vitiko98** [comment]
Can you reproduce now?

**Comment by vitiko98** [comment]
That's a bad link. Use one from the web player. `qobuz-dl` is using "download" as an ID.
