### ISSUE TITLE
KeyError: 'bit_rate'

### ISSUE THREAD

**Issue by zozzza** [vitiko98/qobuz-dl#88]
Pattern error (same with python3.9):
```
Traceback (most recent call last):
  File "/home/~/.local/bin/qobuz-dl", line 8, in <module>
    sys.exit(main())
  File "/home/~/.local/lib/python3.8/site-packages/qobuz_dl/cli.py", line 166, in main
    qobuz.download_list_of_urls(arguments.SOURCE)
  File "/home/~/.local/lib/python3.8/site-packages/qobuz_dl/core.py", line 223, in download_list_of_urls
    self.handle_url(url)
  File "/home/~/.local/lib/python3.8/site-packages/qobuz_dl/core.py", line 203, in handle_url
    self.download_from_id(
  File "/home/~/.local/lib/python3.8/site-packages/qobuz_dl/core.py", line 135, in download_from_id
    downloader.download_id_by_type(
  File "/home/~/.local/lib/python3.8/site-packages/qobuz_dl/downloader.py", line 263, in download_id_by_type
    sanitized_title = sanitize_filename(folder_format.format(**album_attr))
KeyError: 'bit_rate'
```

**Comment by nathom** [comment]
I think you accidentally used the wrong formatting key. Use `bit_depth` not `bit_rate`.

**Comment by zozzza** [comment]
@nathom 
```
  -ff PATTERN, --folder-format PATTERN
                        pattern for formatting folder names, e.g "{artist} - {album} ({year})". available keys: artist, albumartist, album, year, sampling_rate, bit_rate, tracktitle, version. cannot contain
                        characters used by the system, which includes /:<>

```
