### ISSUE TITLE
KeyError: 'copyright'

### ISSUE THREAD

**Issue by stefafishe** [vitiko98/qobuz-dl#89]
I get this error, what shall I do?

Error tagging the file: 'copyright'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qobuz_dl/downloader.py", line 180, in download_and_tag
    tag_function(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qobuz_dl/metadata.py", line 102, in tag_flac
    audio["COPYRIGHT"] = _format_copyright(album["copyright"])
KeyError: 'copyright'

**Comment by nathom** [comment]
Can you share the url you were trying to download?

**Comment by stefafishe** [comment]
> Can you share the url you were trying to download?

Sure: https://play.qobuz.com/album/7619913991010
