### ISSUE TITLE
Qobuzz don't start with Debian 10

### ISSUE THREAD

**Issue by Bavaria1664** [vitiko98/qobuz-dl#91]
Hi,
I'm using debian 10 and since yesterday the client didn't start with any link. Here's the error output:
Traceback (most recent call last):
  File "/home/user/.local/bin/qobuz-dl", line 5, in <module>
    from qobuz_dl import main
  File "/home/user/.local/lib/python3.7/site-packages/qobuz_dl/__init__.py", line 2, in <module>
    from .cli import main
  File "/home/user/.local/lib/python3.7/site-packages/qobuz_dl/cli.py", line 11, in <module>
    from qobuz_dl.core import QobuzDL
  File "/home//user/.local/lib/python3.7/site-packages/qobuz_dl/core.py", line 542
    if (t := essence(item["title"])) not in title_grouped:
          ^
SyntaxError: invalid syntax

Ps; I have the latest version of the client.

**Comment by nathom** [comment]
Your version of python doesn't support the walrus `:=` operator. If you update it, everything should work fine.

**Comment by Bavaria1664** [comment]
> Your version of python doesn't support the walrus `:=` operator. If you update it, everything should work fine.

Thanks for yr reply but after update python the client doesn't work. There's new error:

raceback (most recent call last):
  File "/home/kazaalite/.local/bin/qobuz-dl", line 5, in <module>
    from qobuz_dl import main
  File "/home/kazaalite/.local/lib/python3.9/site-packages/qobuz_dl/__init__.py", line 2, in <module>
    from .cli import main
  File "/home/kazaalite/.local/lib/python3.9/site-packages/qobuz_dl/cli.py", line 11, in <module>
    from qobuz_dl.core import QobuzDL
  File "/home/kazaalite/.local/lib/python3.9/site-packages/qobuz_dl/core.py", line 19, in <module>
    from qobuz_dl.db import create_db, handle_download_id
  File "/home/kazaalite/.local/lib/python3.9/site-packages/qobuz_dl/db.py", line 2, in <module>
    import sqlite3
  File "/usr/local/lib/python3.9/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.9/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
