### ISSUE TITLE
Qobuz still doesn't wotk on Debian 10

### ISSUE THREAD

**Issue by Bavaria1664** [vitiko98/qobuz-dl#92]
Thanks Nathom for yr reply but after update python the client doesn't work. There's  a new error:
Traceback (most recent call last):
  File "/home/user/.local/bin/qobuz-dl", line 5, in <module>
    from qobuz_dl import main
  File "/home/user/.local/lib/python3.9/site-packages/qobuz_dl/__init__.py", line 2, in <module>
    from .cli import main
  File "/home/user/.local/lib/python3.9/site-packages/qobuz_dl/cli.py", line 11, in <module>
    from qobuz_dl.core import QobuzDL
  File "/home/kuser/.local/lib/python3.9/site-packages/qobuz_dl/core.py", line 19, in <module>
    from qobuz_dl.db import create_db, handle_download_id
  File "/home/user/.local/lib/python3.9/site-packages/qobuz_dl/db.py", line 2, in <module>
    import sqlite3
  File "/usr/local/lib/python3.9/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.9/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

Sqlite3 3.35 was already installed

_Originally posted by @Bavaria1664 in https://github.com/vitiko98/qobuz-dl/issues/91#issuecomment-800550534_

**Comment by zozzza** [comment]
@Bavaria1664 
Try under `sudo`:
```
apt-get update
apt-get upgrade
apt-get install sqlite3
```

**Comment by Bavaria1664** [comment]
After installing libsqlite3-dev and compiling python3.9 again, everything is back to normal.
